/**
 * compass_pdf_generated audit-log helper
 *
 * Every PDF generated by /api/pdf/render, /stamp, or /merge writes one row
 * here. Used by FMCSA-audit support · proves WHEN we generated WHICH document
 * for WHICH carrier WHO ran it.
 *
 * Best-effort: log failures never block the actual PDF delivery to the user.
 * The endpoint should always return the PDF · audit gaps are surfaced via
 * the doctor-agent reliability stack rather than user-facing errors.
 *
 * Schema (created by 20260527e_pdf_audit.sql, extended by
 * 20260527f_pdf_version_hash.sql to add template_version + content_hash):
 *   id                uuid pk
 *   carrier_id        uuid · resolved from carrier_members by user_id
 *   user_id           uuid · the caller's auth.uid()
 *   source            text · 'render' | 'stamp' | 'merge'
 *   template_slug     text · e.g. 'letterhead-test', 'hazmat-audit-checklist',
 *                              a filename for stamp, 'merge:N' for merge with N inputs
 *   template_version  text · semver-ish, e.g. '1.0' · only set for 'render'
 *   content_hash      text · 8-char SHA-256 prefix · matches the PDF footer
 *   byte_size         integer · output PDF size in bytes
 *   generated_at      timestamptz default now()
 *
 * RLS · tenant isolation by carrier_id (read-only for the carrier, full
 *       write via service role from this helper).
 */

import { type SupaEnv } from "./supabase-admin";

const SUPABASE_HEADERS = (sr: string) => ({
  apikey: sr,
  Authorization: `Bearer ${sr}`,
  Accept: "application/json",
  "Content-Type": "application/json",
  Prefer: "return=minimal",
});

export type PdfAuditEntry = {
  user_id: string;
  source: "render" | "stamp" | "merge";
  template_slug: string;
  template_version?: string;
  content_hash?: string;
  byte_size: number;
};

export async function logPdfGenerated(env: SupaEnv, entry: PdfAuditEntry): Promise<void> {
  if (!env.SUPABASE_URL || !env.SUPABASE_SERVICE_ROLE) return; // no-op when not configured

  // Resolve carrier_id from the caller's membership · first carrier wins (the
  // single-carrier-per-user assumption matches the rest of our app today).
  let carrier_id: string | null = null;
  try {
    const r = await fetch(
      `${env.SUPABASE_URL}/rest/v1/carrier_members?user_id=eq.${entry.user_id}&select=carrier_id&limit=1`,
      { headers: SUPABASE_HEADERS(env.SUPABASE_SERVICE_ROLE) }
    );
    if (r.ok) {
      const rows = await r.json() as Array<{ carrier_id: string }>;
      carrier_id = rows[0]?.carrier_id || null;
    }
  } catch { /* swallow */ }
  if (!carrier_id) return; // can't audit without a carrier · drop the entry

  // Insert · ignore failures
  await fetch(`${env.SUPABASE_URL}/rest/v1/compass_pdf_generated`, {
    method: "POST",
    headers: SUPABASE_HEADERS(env.SUPABASE_SERVICE_ROLE),
    body: JSON.stringify({
      carrier_id,
      user_id: entry.user_id,
      source: entry.source,
      template_slug: entry.template_slug.slice(0, 120),
      template_version: entry.template_version || null,
      content_hash: entry.content_hash || null,
      byte_size: entry.byte_size,
    }),
  }).catch(() => { /* non-fatal */ });
}
